### ISSUE TITLE
emm

### ISSUE THREAD

**Issue by EmbraceDC** [inteoryx/twitter-video-dl#23]
Traceback (most recent call last):
  File "C:\Users\Phantasm\Downloads\twitter-video-dl-main\twitter-video-dl-main\twitter-video-dl.py", line 25, in <module>
    tvdl.download_video(args.twitter_url, file_name)
  File "C:\Users\Phantasm\Downloads\twitter-video-dl-main\twitter-video-dl-main\src\twitter_video_dl\twitter_video_dl.py", line 382, in download_video
    assert len(
           ^^^^
AssertionError: Could not find any mp4s to download.  Make sure you are using the correct url.  If you are, then file a GitHub issue and copy and paste this message.  Tweet url: https://twitter.com/0521MissA/status/1664475514055315456

**Comment by inteoryx** [comment]
This happens because Twitter won't let unauthenticated accounts download age-restricted videos.  In order to fix this the download script would need to authorize itself - that would involve asking the user for a password and I don't really want to do that.

Sorry, but this issue won't be fixed.
